### PR TITLE
Standard MageError class for user-land

### LINKED ISSUE #135: RFC: MageError class(es)
In async user commands, throw errors will either return `error.code` or `error.message`. But when I throw right now, I often do:

```javascript
throw new Error('Invalid request, partner set deck')
```

We should probably promote something like:

```javascript
throw new MageError({
  code: SomeEnumOrMap.ErrorCode,
  message: 'Something bery bery baaad happened',
  details: {
    some,
    request,
    data
  }
})
```

This would:

  1. Encourage developers to set explicit error codes which can then be shared with the client (and which the client should be able to react to)
  2. Still log the message
  3. Attach error-related data with the error instead of having to log those separately
  4. Provide a base class to extend:

> lib/consts/errors.ts

```typescript
import { MageError } from 'mage'

// throw new QueryError(typedDetails)
export QueryError extends MageError<IQueryDetails> {
  public code = 'query_error'
  public message = 'Query failed unexpectedly'
}
```

### PR DESCRIPTION
**Pull request by stelcheck**
This should help:

  1. Standardize error management
  2. Allow for throwing errors (and interrupt the execution flow)
     without necessarily logging an error
  3. Allow to attach additional details to the error to be logged, thus
     removing the need for an additional log call prior to throwing
  4. Attach a response code to be sent to the client; this also has the
     advantage of being part of the log data, thus making it easier
     to search for error occurrences by code instead of by message
     content.

Requires #112 
Fixes #135

### CODE REVIEW

**Comment by stelcheck** [comment]
Adding the label WIP just because documentation would be needed before merging.

**Comment by stelcheck** [comment]
Documentation was completed, ready for review!

File: lib/mage/MageError.js [hunk 1]
```diff
@@ -0,0 +1,12 @@
+'use strict';
+
+module.exports = class MageError extends Error {
+	constructor(data) {
+		super(data.message || 'Mage Error');
+
+		this.code = data.code || 'server';
+		this.level = data.level || 'error';
```
Comment (ronkorving) [inline lib/mage/MageError.js]: If the level is unrecognized, should we default it to `alert` or something, so that it can be fixed?

Throwing or otherwise seems unwise, since the user is trying to log something here, and we shouldn't get in the way of that. But especially because of that, it does make sense to detect it, fix it on the spot, and escalate it.

File: docs-sources/includes/_Modules.md [hunk 2]
```diff
@@ -308,3 +308,68 @@ instead of relying on MAGE to serialize the return data. This can be useful when
...
+		super(data);
+
+    // Code to return to the client (default: server)
+    this.code = 'server';
+
+    // Log level to use to log this error (default: error)
+    this.level = 'warning';
+
+    // Details to log alongside the message (default: undefined)
+    this.details = data.details;
```
Comment (ronkorving) [inline docs-sources/includes/_Modules.md]: `details` in the logger used to be like a "long message". Here I guess it's a dictionary (from looking at the code example below)?

File: lib/mage/MageError.ts [hunk 3]
```diff
@@ -0,0 +1,53 @@
...
+     * The log level to use when logging this error (default: error)
+     *
+     * Some types of errors are perfectly normal; for instance,
+     * a user failing to authenticate may throw an error, but
+     * you might not want to have it logged as an error.
+     *
+     * Setting the level will allow you to decide whether this
+     * error should be ignored, considered benign, or serious.
+     */
+    level?: 'debug' | 'warning' | 'error' | 'alert' | 'emergency',
```
Comment (ronkorving) [inline lib/mage/MageError.ts]: Does debug have a place in this? Also, I think `critical` is missing.

File: lib/mage/MageError.ts [hunk 4]
```diff
@@ -0,0 +1,53 @@
...
+
+    /**
+     * The error code
+     *
+     * This code will generally be the code that will be returned
+     * to the client if this error is thrown during a user command
+     * request.
+     */
+    code: string,
```
Comment (ronkorving) [inline lib/mage/MageError.ts]: I believe `state` allows `code` to be both `string` or `number`.

File: lib/mage/MageError.ts (hunk 3 above)
Comment (stelcheck) [reply lib/mage/MageError.ts]: Who knows :D I would simply support all log levels just to make sure we have more choice.

File: lib/mage/MageError.ts (hunk 4 above)
Comment (stelcheck) [reply lib/mage/MageError.ts]: What happens if its a number?

Comment (stelcheck) [reply lib/mage/MageError.ts]: I see the code is internally stringified.

Personally, I would prefer to be explicit at least in typescript about this - I'd hate to see confusion with a dev returning a number only to wonder why it's being received as a string on the client.

File: lib/mage/MageError.ts (hunk 3 above)
Comment (stelcheck) [reply lib/mage/MageError.ts]: I take that back. The idea behind debug being in the list was that some userland errors are perfectly natural, and you wouldn't necessarily want to log them in production but still make sure to return a specific error code (insufficient funds, etc)

File: lib/mage/MageError.js (hunk 1 above)
Comment (stelcheck) [reply lib/mage/MageError.js]: Defaulting to alert but logging a warning about the discrepancy.

File: docs-sources/includes/_Modules.md (hunk 2 above)
Comment (ronkorving) [reply docs-sources/includes/_Modules.md]: Fine as-is 👍
