### PR TITLE
zookeeper connection loss

### LINKED ISSUE #52: zookeeper: connection lost
```plaintext
m-42 - 13:14:46.113     <alert> [MAGE msgServer] Exception: CONNECTION_LOSS[-4]
  data: {
    "code": -4,
    "name": "CONNECTION_LOSS",
    "file": "ConnectionManager.js",
    "line": 720,
    "offset": 28,
    "type": "CONNECTION_LOSS",
    "stack": [
      "ConnectionManager.queue (node_modules/node-zookeeper-client/lib/ConnectionManager.js:720:28)",
      "node_modules/node-zookeeper-client/index.js:799:36",
      "async.whilst.args (node_modules/node-zookeeper-client/index.js:125:13)",
      "Object.async.whilst (node_modules/node-zookeeper-client/node_modules/async/lib/async.js:619:13)",
      "Timeout._onTimeout (node_modules/node-zookeeper-client/node_modules/async/lib/async.js:623:23)",
      "ontimeout (timers.js:386:14)",
      "tryOnTimeout (timers.js:250:5)",
      "Timer.listOnTimeout (timers.js:214:5)"
    ]
  }
```

I do not know if its an issue, but I did not see any logs pertaining to reconnect attempts following that. This would mean that some clustering issues would likely occur under adverse network conditions.

Assigning @ronkorving and myself to investigate whether 1. There is a reconnect attempt, and 2. What is the reconnect logic, and 3. Make sure that a `notice` log level is emitted for both zookeeper disconnect and reconnect.

### PR DESCRIPTION
**Pull request by stelcheck**
Fixes #52

To reviewers; please make sure to read the portion of the code being referred to in node-zookeeper-client.

### CODE REVIEW

File: lib/msgServer/index.js [hunk 1]
```diff
@@ -480,9 +480,13 @@ function setupDiscovery() {
 
 
 	service.on('error', function (error, service) {
-		if (!service) {
+		if (!service && error.name !== 'CONNECTION_LOSS') {
```
Comment (ronkorving) [inline lib/msgServer/index.js]: If there is no service, but the error is CONNECTION_LOSS, we will move on beyond this if-statement and have an uncaught exception on line 493. I expect you'll wanna split this up into 2 cases, one for no service and one for non-CONNECTION_LOSS errors.

Comment (stelcheck) [inline lib/msgServer/index.js]: Got it.

**Comment by stelcheck** [comment]
@ronkorving fixed the code, and we will now log a warning to track how frequently this happens.

File: lib/msgServer/index.js [hunk 2]
```diff
@@ -480,6 +480,18 @@ function setupDiscovery() {
...
 
 	service.on('error', function (error, service) {
+		if (error.name !== 'CONNECTION_LOSS') {
+			// We ignore connection losses since any persisting connnectivity issues
+			// should be managed by the other event handlers, and connection loss for in-flight requests
+			// will be retried by zookeper.
+			//
+			// See https://github.com/alexguan/node-zookeeper-client/blob/master/index.js#L138 for more details
+			return logger.warning
+				.details('node-zookeeper-client will retry the query; you may ignore')
```
Comment (ronkorving) [inline lib/msgServer/index.js]: We're inside `msgServer` here though, not the zookeeper SD engine. So even if this plays nice with Consul and mDNS (because of error.name), is there not a more appropriate place to put this?

Comment (stelcheck) [inline lib/msgServer/index.js]: Probably. Any suggestions?

**Comment by stelcheck** [comment]
Moved filtering to the zookeeper engine.
