### PR TITLE
invalid session and unstable connections

### LINKED ISSUE #108: zookeeper: service discovery should stop and reconnect if session is found to be invalid
While trying to reproduce #52, I just made an experiment of restarting zookeeper to try to trigger this issue, and got the following results in the zookeeper logs (repeating forever):

```
2017-08-03 06:26:29,385 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxnFactory@192] - Accepted socket connection from /172.17.0.1:57610
2017-08-03 06:26:29,385 [myid:] - WARN  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:ZooKeeperServer@896] - Connection request from old client /172.17.0.1:57610; will be dropped if server is in r-o mode
2017-08-03 06:26:29,385 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:ZooKeeperServer@915] - Refusing session request for client /172.17.0.1:57610 as it has seen zxid 0x6 our last zxid is 0x0 client must try another server
2017-08-03 06:26:29,385 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxn@1044] - Closed socket connection for client /172.17.0.1:57610 (no session established for client)
2017-08-03 06:26:29,395 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxnFactory@192] - Accepted socket connection from /172.17.0.1:57614
2017-08-03 06:26:29,395 [myid:] - WARN  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:ZooKeeperServer@896] - Connection request from old client /172.17.0.1:57614; will be dropped if server is in r-o mode
2017-08-03 06:26:29,395 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:ZooKeeperServer@915] - Refusing session request for client /172.17.0.1:57614 as it has seen zxid 0xd our last zxid is 0x0 client must try another server
2017-08-03 06:26:29,395 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxn@1044] - Closed socket connection for client /172.17.0.1:57614 (no session established for client)
```

Meanwhile, MAGE reports no issues; it appears just to try to reconnect forever.

### PR DESCRIPTION
**Pull request by stelcheck**
In particular, this solves an issue where the underlying client
connection would simply rotate over the list of server forever
if the client has an invalid session. This causes issue
when running, for instance, a single ZK node, and restarting
it while a MAGE cluster is connected to it (all nodes end up
spamming the ZooKeeper instance once it comes back).

Fixes #108

### CODE REVIEW

File: lib/serviceDiscovery/engines/zookeeper/index.js [hunk 1]
```diff
@@ -118,30 +122,81 @@ function ZooKeeperService(name, type, options) {
...
+		}, CONNECT_TIMEOUT);
+	});
+
+	if (!this.closed) {
+		logger.verbose('ZooKeeper client connecting to', options.hosts);
+		return this.client.connect();
+	}
 
-	this.client.connect();
+	if (this.discovering !== false) {
```
Comment (christopherobin) [inline lib/serviceDiscovery/engines/zookeeper/index.js]: Wait, is `this.closed === true` then we run discovery and announce?

Comment (stelcheck) [inline lib/serviceDiscovery/engines/zookeeper/index.js]: In order:

  1. this.closed === true means we must be connected and makes no assumption as to whether we either announce or discover
  2. this.discovering means we were discovering prior to the reset, and are expected to keep on discovering
  3. this.announcing means we were announcing prior to the reset, and are expected to keep on announcing

Note that close sets all three values to false: https://github.com/mage/mage/pull/113/files/b5686cfc24918b5f886cc0890bb9a84604a587a2#diff-df9e000e82d7187631d7095d0604e1a7R420

Comment (christopherobin) [inline lib/serviceDiscovery/engines/zookeeper/index.js]: Can we have a case where `closed` is true but `discovering` and `announcing` are also true?

Comment (stelcheck) [inline lib/serviceDiscovery/engines/zookeeper/index.js]: I don't believe so

Comment (christopherobin) [inline lib/serviceDiscovery/engines/zookeeper/index.js]: Then I don't understand the logic:

```ruby
client = createClient()
client.setEvents()
if not closed return client.connect()
if discover then discover()
if announcing then announce()
check if we are connected after timeout?
```

Since we return on running `connect` what is the point of checking for the connection or trying to announce/discover on a closed connection?

Comment (stelcheck) [inline lib/serviceDiscovery/engines/zookeeper/index.js]: I think the return might be a mistake (although everything appears to work fine?). I'll have a look.

Comment (christopherobin) [inline lib/serviceDiscovery/engines/zookeeper/index.js]: I feel like the code instead should be:

```javascript
if (this.closed) {
	return;
}

logger.verbose('ZooKeeper client connecting to', options.hosts);
this.client.connect();
```

Comment (stelcheck) [inline lib/serviceDiscovery/engines/zookeeper/index.js]: Fixed.
