### PR TITLE
mmrp: generate ID based on IP list

### LINKED ISSUE #153: zookeeper: nodes should be named based on uri, not clusterId
While working on https://github.com/mage/mage/pull/152 I realized that ZooKeeper could potentially leave lingering nodes behind. The aforementioned PR solves the main issue with that, however, the cluster information will still take up to 30 seconds to become consistent. This means that systems relying on service discovery information - such as https://www.npmjs.com/package/mage-module-shard - will route traffic based on an inconsistent view of the cluster.

Instead, what we should do is:

  1. Name ZooKeeper nodes using the URI, instead of the cluster ID. This should reduce the number of lingering nodes after a crash-and-restart
  2. Make sure that the zookeeper service discovery backend propagates correctly the overwrite. 

While this does not eliminate all lingering node cases, it should help reduce their number - essentially, the only time where nodes may be left to linger is if a cluster is downsized, and nodes are killed with `SIGKILL`.

@ronkorving @christopherobin Does that make sense to you guys?

### PR DESCRIPTION
**Pull request by stelcheck**
- Use the list of local IPs to determine a consistent cluster ID.
- Zookeeper: generate a consistent ID for storing entry into ZooKeeper

Requires #152 
Fixes #153

### CODE REVIEW

**Comment by stelcheck** [comment]
Could we get this moving forward? Just realized I need this for a project I am working on.

**Comment by AlmirKadric** [comment]
i reviewed this, and nothing really stands out
this being said i would need to really go deep into the system to properly review logical issues
very hard to do that from a diff
cc: @ronkorving

File: lib/serviceDiscovery/helpers.js [hunk 1]
```diff
@@ -0,0 +1,52 @@
...
+let announceIps;
+
+/**
+ * Builds a list of every announce-able ips on the server
+ *
+ * @returns {string} The ip list
+ * @todo Support from env variables?
+ */
+exports.getAnnounceIps = memoizee(function () {
+	if (announceIps) {
```
Comment (ronkorving) [inline lib/serviceDiscovery/helpers.js]: You're double memoizing :)
Once by doing it yourself, and once with memoizee.

File: lib/serviceDiscovery/helpers.js [hunk 2]
```diff
@@ -0,0 +1,52 @@
+'use strict';
+
+const os = require('os');
+const crypto = require('crypto');
+const memoizee = require('memoizee');
+
+const interfaces = os.networkInterfaces();
+const ifaceNames = Object.keys(interfaces);
+
+// choose the first valid ip as the one we will announce
```
Comment (ronkorving) [inline lib/serviceDiscovery/helpers.js]: I can't tell what this comment applies to... Not to the `let announceIps` below I assume.

File: lib/serviceDiscovery/helpers.js [hunk 3]
```diff
@@ -0,0 +1,52 @@
...
+			if (address.internal) {
+				continue;
+			}
+
+			// found it, store it and break
+			announceIps.push(address.address);
+		}
+	}
+
+	// just in case
```
Comment (ronkorving) [inline lib/serviceDiscovery/helpers.js]: How is this "just in case"?

File: lib/serviceDiscovery/helpers.js [hunk 4]
```diff
@@ -0,0 +1,52 @@
...
+
+		for (var j = 0; j < addresses.length; j++) {
+			var address = addresses[j];
+
+			// skip anything that doesn't interest us
+			if (address.internal) {
+				continue;
+			}
+
+			// found it, store it and break
```
Comment (ronkorving) [inline lib/serviceDiscovery/helpers.js]: There's no `break`

File: lib/serviceDiscovery/helpers.js [hunk 5]
```diff
@@ -0,0 +1,52 @@
...
+const memoizee = require('memoizee');
+
+const interfaces = os.networkInterfaces();
+const ifaceNames = Object.keys(interfaces);
+
+// choose the first valid ip as the one we will announce
+let announceIps;
+
+/**
+ * Builds a list of every announce-able ips on the server
```
Comment (ronkorving) [inline lib/serviceDiscovery/helpers.js]: English: "every announce-able IP" (not plural)

File: lib/serviceDiscovery/helpers.js [hunk 6]
```diff
@@ -0,0 +1,52 @@
...
+		}
+	}
+
+	// just in case
+	return announceIps;
+});
+
+exports.generateId = function (port) {
+	const generator = crypto.createHmac('sha256', 'secret');
+	exports.getAnnounceIps().forEach((ip) => generator.update(ip));
```
Comment (ronkorving) [inline lib/serviceDiscovery/helpers.js]: I understand you're trying to get this ID to be consistent for the machine this is running on, but since we're doing `Object.keys` on line 8 and not sorting, I don't think order can be guaranteed. It would probably be wise to add a `.sort()` on this line:

```js
exports.getAnnounceIps().slice().sort().forEach((ip) => generator.update(ip));
```

(turns that code a bit ugly now, but ... I hope it illustrates the point)

File: lib/msgServer/mmrp/index.js [hunk 7]
```diff
@@ -103,11 +98,33 @@ function MmrpNode(role, cfg, clusterId) {
...
 			this.routerPort = parseInt(routerUri.substr(routerUri.lastIndexOf(':') + 1), 10);
+
+			// Share MMRP master port through the environment
+			process.env[ENV_MAGE_MMRP_MASTER_PORT] = this.routerPort;
+
+			// Generate the cluster ID based on the port the master listens on
+			this.clusterId = serviceDiscovery.helpers.generateId(this.routerPort);
+
+			// Set the identity of the router socket to the cluster ID
+			this.router.setsockopt(zmq.ZMQ_IDENTITY, new Buffer(this.clusterId));
```
Comment (ronkorving) [inline lib/msgServer/mmrp/index.js]: I notice this wasn't done before for the router, was it? Any idea why and how does introducing it here change the behavior?

File: lib/msgServer/mmrp/index.js [hunk 8]
```diff
@@ -103,11 +98,33 @@ function MmrpNode(role, cfg, clusterId) {
...
 		}
+	} else {
+		// Retrieve the cluster ID from the environment
+		const masterPort = process.env[ENV_MAGE_MMRP_MASTER_PORT];
```
Comment (ronkorving) [inline lib/msgServer/mmrp/index.js]: Just for consistency, you may want to `parseInt` this.

File: lib/msgServer/mmrp/index.js [hunk 9]
```diff
@@ -103,11 +98,33 @@ function MmrpNode(role, cfg, clusterId) {
...
+
+		// Generate the cluster ID based on the port the master listens on
+		this.clusterId = serviceDiscovery.helpers.generateId(masterPort);
 	}
 
+	// dealer
+
+	this.identity = this.isRelay ? this.clusterId : createDealerIdentity(this.clusterId);
```
Comment (ronkorving) [inline lib/msgServer/mmrp/index.js]: I get the impression from looking at the code that `this.clusterId` could be undefined. That is, there may be code paths that lead to it not getting set.

File: lib/msgServer/mmrp/index.js [hunk 10]
```diff
@@ -130,28 +147,64 @@ exports.MmrpNode = MmrpNode;
...
+	const relay = this.relays[clusterId];
 
 	// if we're already connected to this URI, we ignore this request
 
 	if (relay && relay.uri) {
-		if (cb) {
-			cb();
-		}
-		return;
+		return callMeMaybe(cb);
```
Comment (ronkorving) [inline lib/msgServer/mmrp/index.js]: Haven't you ruled this out by the loop you introduce above? Either we've returned because the existing relay is newer, or we've deleted the existing one.

File: lib/msgServer/mmrp/index.js [hunk 11]
```diff
@@ -130,28 +147,64 @@ exports.MmrpNode = MmrpNode;
...
+	const timestamp = data.timestamp;
+
 	// we cannot connect through routers (long routes), we are establishing a direct connection
 
 	assert.strictEqual(typeof uri, 'string');
 	assert.strictEqual(typeof clusterId, 'string');
 
-	var route = [clusterId];
-	var relay = this.relays[clusterId];
+	// check if other relay(s) with the same URI exist, and disconnect them;
```
Comment (ronkorving) [inline lib/msgServer/mmrp/index.js]: Except.. you don't really disconnect them. I understand you don't really want to explain that weird disconnect situation twice, but .. yeah :-/

File: lib/msgServer/mmrp/index.js [hunk 12]
```diff
@@ -130,28 +147,64 @@ exports.MmrpNode = MmrpNode;
...
+			return callMeMaybe(cb);
+		}
+
+		logger.verbose.data({
+			oldRelayId: relayClusterId,
+			newRelayId: clusterId
+		}).log(this.clusterId, 'found relay with same uri, removing the relay');
+
+		// We delete the relay reference, but do not disconnect; quick disconnect-reconnect
+		// appear to confuse ZeroMQ, and may permanently break the connection in some cases.
```
Comment (ronkorving) [inline lib/msgServer/mmrp/index.js]: Some more information, perhaps documentation or a link to a gist, or .. you name it, would be really helpful for future generations.

File: lib/msgServer/mmrp/index.js [hunk 13]
```diff
@@ -168,25 +221,29 @@ MmrpNode.prototype.connect = function (uri, clusterId, cb) {
...
 
-			logger.verbose(this.clusterId, 'dealer disconnecting from', uri, '(cluster: ' + clusterId + ')');
+	if (!relay) {
+		return verbose.log('dealer disconnect requested but relay does not exist');
+	}
 
-			this.dealer.disconnect(uri);
-			return;
-		}
+	if (uri !== relay.uri) {
```
Comment (ronkorving) [inline lib/msgServer/mmrp/index.js]: How could this ever happen?

File: lib/serviceDiscovery/helpers.js (hunk 2 above)
Comment (stelcheck) [reply lib/serviceDiscovery/helpers.js]: No idea. Guessing that was a comment from a prior prototype implementation I had... apologies for the noise.

File: lib/serviceDiscovery/helpers.js (hunk 3 above)
Comment (stelcheck) [reply lib/serviceDiscovery/helpers.js]: Well... just in case you care? 

*sigh* guess that was a late night commit. Again, apologies for that.

File: lib/serviceDiscovery/helpers.js (hunk 4 above)
Comment (stelcheck) [reply lib/serviceDiscovery/helpers.js]: Think I remember now: initially I wanted to use the first announce-able IP, but I didn't trust that this would be consistent enough on all platform and ended up using **all** announced IPs instead. Comments are from that initial concept.

File: lib/serviceDiscovery/helpers.js (hunk 6 above)
Comment (stelcheck) [reply lib/serviceDiscovery/helpers.js]: Good catch. I'll sort in getAnnounceIps instead though.

File: lib/msgServer/mmrp/index.js (hunk 7 above)
Comment (stelcheck) [reply lib/msgServer/mmrp/index.js]: Been two months + so memory is fuzzy. But IIRC, in the past indentity was ephemeral, so setting an explicit identity didn't matter. Now that the ID is consistent across reboots, setting it is necessary to ensure queued messages will find their way to that node post-reboot.

File: lib/msgServer/mmrp/index.js (hunk 9 above)
Comment (stelcheck) [reply lib/msgServer/mmrp/index.js]: I think its undefined if you are in single mode (when zmq.ZMQ_LAST_ENDPOINT on line 100 returns nothing).

File: lib/msgServer/mmrp/index.js (hunk 11 above)
Comment (stelcheck) [reply lib/msgServer/mmrp/index.js]: Suggestions?

File: lib/msgServer/mmrp/index.js (hunk 13 above)
Comment (stelcheck) [reply lib/msgServer/mmrp/index.js]: I'd say its something we'd want to have blow up in our face if it *did* ever happen.

File: lib/msgServer/mmrp/index.js (hunk 10 above)
Comment (stelcheck) [reply lib/msgServer/mmrp/index.js]: I think that's incorrect:

1. We go through the list of nodes
2. We continue if this node is the node we are connecting to
3. We continue if the URIs do not match
4. If we find a more recent node, we return, since the node we are trying to connect is outdated
5. We disconnect any node reaching this point

Therefore, once we reach that point, it's entirely possible that we have disconnected a bunch of servers but were not connected ourselves.

**Comment by stelcheck** [comment]
Have gone through most of the comments, fixed what I could and left follow up comments elsewhere, except for https://github.com/mage/mage/pull/166#discussion_r153679396 for which I'll need to go through the ZMQ mailing list (IIRC that's where I found some info on that subject).

File: lib/serviceDiscovery/helpers.js (hunk 6 above)
Comment (stelcheck) [reply lib/serviceDiscovery/helpers.js]: Sorting there actually ends up having an adverse effect. See https://github.com/mage/mage/pulls for more details.
