### PR TITLE
daemon: multiple fixes

### LINKED ISSUE #136: `npm reload` crashes
```
Reloading... (pid: 8771)
m-8844  - 14:59:24.103 <emergency> [MAGE processManager] Uncaught exception: Cannot read property 'pipe' of undefined
  error: {
    "type": "TypeError",
    "file": "index.js",
    "line": 147,
    "offset": 13,
    "stack": [
      "process.sigFailedHandler (node_modules/mage/lib/daemon/index.js:147:13)",
      "emitNone (events.js:86:13)",
      "process.emit (events.js:188:7)",
      "Signal.wrap.onsignal (internal/process.js:215:44)"
    ]
  }
```

### LINKED ISSUE #137: `npm run reload` causes heapdumps
Both the `heapdump` module and `reload` share the same signal, so triggering one always triggers the others. This means that one cannot take heapdumps without triggering reloads.

### PR DESCRIPTION
**Pull request by stelcheck**
Demo video: https://asciinema.org/a/ASEQCfwIdNzFZErCGhOTXi9w6

  - `reload` SIGUSR2 -> SIGALARM (fixes #137)
  - `reload`: reverting to `spawn` instead of of `fork` (fixes #136)
  - Using a named pipe for sharing logs between MAGE and the daemonized
  - start, stop, restart and reload show logs
  - all logs are always shown (instead of only errors on crashes)
  - colorization is forced when daemonized

### CODE REVIEW

**Comment by stelcheck** [comment]
Closing, because I don't really care any longer.

**Comment by stelcheck** [comment]
Closed the wrong issue... apologies for the confusion.

File: lib/daemon/index.js [hunk 1]
```diff
@@ -1,22 +1,56 @@
...
 var timeouts = mage.core.config.get(['daemon', 'timeouts']) || {};
 
+function disableDaemonizedStdio(commandPid) {
+	if (!commandPid) {
+		return;
+	}
+
+	// Send stdio to a black hole
+	function disable(io) {
+		io.write = () => true;
```
Comment (ronkorving) [inline lib/daemon/index.js]: The previous code was `() => false;`.
What changed about that?

Comment (stelcheck) [reply lib/daemon/index.js]: `write` returns `true` in real life. I was fearing that `false` might somehow cause issues with dependencies.

Comment (ronkorving) [reply lib/daemon/index.js]: Because of exit logs?

Comment (stelcheck) [reply lib/daemon/index.js]: No, just because 'false' *may* be considered as an error. At any rate, returning `true` is more consistent.

File: lib/daemon/index.js [hunk 2]
```diff
@@ -415,23 +460,20 @@ function removeSocketFiles() {
...
-				stdout,
-				stderr
-			} = process;
+	// Disable stdout/stderr if we are starting daemonized
+	processManager.once('started', () => disableDaemonizedStdio(commandPid));
 
-			stdout.write = () => false;
-			stderr.write = () => false;
-		}
+	// Upon exitting, check if we can forward exit logs
```
Comment (ronkorving) [inline lib/daemon/index.js]: Very nitpicky, but suggestion when it comes to comment writing. I try to avoid "check if", because usually there's something we do, if ...

Compare to: `// Upon exiting, try to forward exit logs`
(Also, `exiting` has 1 t)

File: lib/daemon/index.js (hunk 1 above)
Comment (stelcheck) [reply lib/daemon/index.js]: According to the Node.js doc:

```
Returns: <boolean> false if the stream wishes for the calling code to wait for the 'drain' 
event to be emitted before continuing to write additional data; otherwise true.
```

Since we are *never* going to call drain, true is safer.

Comment (ronkorving) [reply lib/daemon/index.js]: Ah yes, indeed 👍 
But friendly cc to @christopherobin who was involved in the original `return false` I think?

Comment (stelcheck) [reply lib/daemon/index.js]: I was the one who wrote that for him, he just picked up the code from a separate branch I had created to solve some issues he was having with his initial PR.

**Comment by stelcheck** [comment]
Fixed the comment.

File: lib/daemon/index.js [hunk 3]
```diff
@@ -480,11 +522,15 @@ exports.init = function () {
 			}
 		}
 
+		var commandPid = getFilePid(CMD_LOCK_FILE);
```
Comment (ronkorving) [inline lib/daemon/index.js]: Definitely not a blocker, but feel free to `const` all-the-things ;)

File: lib/daemon/index.js [hunk 4]
```diff
@@ -1,22 +1,56 @@
...
+	function disable(io) {
+		io.write = () => true;
+	}
+
+	disable(process.stdout);
+	disable(process.stderr);
+}
+
+function setDaemonizedStdio(commandPid) {
+	if (!commandPid) {
```
Comment (ronkorving) [inline lib/daemon/index.js]: The PID is not relevant to this function, so to pass it... is quite confusing (I know, because I've been trying to make sense of this PR in review ;))

Would it not make more sense to have a boolean returning function somewhere (instead of a PID, but by all means on the same basis), and if that boolean is false, to not *call* functions like (un)setDaemonizedStdio?

Comment (stelcheck) [reply lib/daemon/index.js]: The issue is that you then end up having to carry a conditional *everywhere* (well. 4 places). 

I'll try to make this look a bit clearer.

File: lib/daemon/index.js [hunk 5]
```diff
@@ -98,10 +132,27 @@ function destroyFilePid(filename) {
...
+function getCommandAppStatus() {
+	return !!getFilePid(CMD_LOCK_FILE);
+}
+
 
 function App(runstate, pid) {
+	// Force color output on logs - this is necessary so
+	// that the daemonized master process as well as its workers
+	// output colorized logs when running start/stop/restart/etc.
+	process.env.FORCE_COLOR = 1;
```
Comment (ronkorving) [inline lib/daemon/index.js]: This probably has some drawbacks, no?

Comment (stelcheck) [reply lib/daemon/index.js]: You are right. What we can do is have the daemonizer filter colors if it doesn't support them.

Comment (stelcheck) [reply lib/daemon/index.js]: Just added the code to do that to this PR
